"""added 1 to 1 relationship between vacancy and vacnacy hours

Revision ID: 00155b3b42fc
Revises: 63ac519a1979
Create Date: 2022-11-28 20:53:24.973421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00155b3b42fc'
down_revision = '63ac519a1979'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('hours_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancy', 'vacancy_hours', ['hours_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancy', type_='foreignkey')
    op.drop_column('vacancy', 'hours_category_id')
    # ### end Alembic commands ###
