"""added vacancy description tag table

Revision ID: 0cd045d2fe49
Revises: 7aef8746dbd2
Create Date: 2022-11-28 21:18:19.107394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd045d2fe49'
down_revision = '7aef8746dbd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy_description_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_description_tag_id'), 'vacancy_description_tag', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_description_tag_id'), table_name='vacancy_description_tag')
    op.drop_table('vacancy_description_tag')
    # ### end Alembic commands ###
