"""added relationship on vacancy and vacancy category

Revision ID: 0ef2459f860b
Revises: efaec9b4f079
Create Date: 2022-11-28 21:10:44.687210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef2459f860b'
down_revision = 'efaec9b4f079'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('vacancy_category_id', sa.Integer(), nullable=True))
    op.add_column('vacancy', sa.Column('vacancy_hours_id', sa.Integer(), nullable=True))
    op.drop_constraint('vacancy_hours_category_id_fkey', 'vacancy', type_='foreignkey')
    op.create_foreign_key(None, 'vacancy', 'vacancy_hours', ['vacancy_hours_id'], ['id'])
    op.create_foreign_key(None, 'vacancy', 'vacancy_category', ['vacancy_category_id'], ['id'])
    op.drop_column('vacancy', 'hours_category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('hours_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vacancy', type_='foreignkey')
    op.drop_constraint(None, 'vacancy', type_='foreignkey')
    op.create_foreign_key('vacancy_hours_category_id_fkey', 'vacancy', 'vacancy_hours', ['hours_category_id'], ['id'])
    op.drop_column('vacancy', 'vacancy_hours_id')
    op.drop_column('vacancy', 'vacancy_category_id')
    # ### end Alembic commands ###
