"""added active to vacancy

Revision ID: 57094510114c
Revises: 00155b3b42fc
Create Date: 2022-11-28 21:01:41.860065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57094510114c'
down_revision = '00155b3b42fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy', 'active')
    # ### end Alembic commands ###
