"""added vacancy hours table

Revision ID: 63ac519a1979
Revises: a967332b1a6e
Create Date: 2022-11-28 20:45:52.945270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ac519a1979'
down_revision = 'a967332b1a6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy_hours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hours_category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_hours_id'), 'vacancy_hours', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_hours_id'), table_name='vacancy_hours')
    op.drop_table('vacancy_hours')
    # ### end Alembic commands ###
