"""added vacancy description table

Revision ID: 7aef8746dbd2
Revises: 0ef2459f860b
Create Date: 2022-11-28 21:14:20.746152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aef8746dbd2'
down_revision = '0ef2459f860b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy_description',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_description_id'), 'vacancy_description', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_description_id'), table_name='vacancy_description')
    op.drop_table('vacancy_description')
    # ### end Alembic commands ###
