"""added relationship vacancy and description

Revision ID: ae1ef034aafb
Revises: 5a87e6107e56
Create Date: 2022-11-28 21:30:56.486331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1ef034aafb'
down_revision = '5a87e6107e56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy_description', sa.Column('vacancy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancy_description', 'vacancy', ['vacancy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancy_description', type_='foreignkey')
    op.drop_column('vacancy_description', 'vacancy_id')
    # ### end Alembic commands ###
