"""added vacancy category table

Revision ID: efaec9b4f079
Revises: 57094510114c
Create Date: 2022-11-28 21:05:17.254294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efaec9b4f079'
down_revision = '57094510114c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_category_id'), 'vacancy_category', ['id'], unique=False)
    op.add_column('vacancy_hours', sa.Column('category', sa.String(), nullable=False))
    op.drop_column('vacancy_hours', 'hours_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy_hours', sa.Column('hours_category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('vacancy_hours', 'category')
    op.drop_index(op.f('ix_vacancy_category_id'), table_name='vacancy_category')
    op.drop_table('vacancy_category')
    # ### end Alembic commands ###
